---
apiVersion: v1
kind: Service
metadata:
  name: comm-8080
  namespace: sapidblue
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
  selector:
    app: comm-8080