---
apiVersion: v1
kind: Service
metadata:
  name: bonus-front
  namespace: sapidblue
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: bonus-front