kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
  namespace: sapidblue-mysql
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer