kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sapidblue-mysql-data
  namespace: qa-mysql
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi