apiVersion: v1
kind: Service
metadata: 
  name: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    nodePort: 30036
    targetPort: 3306