---
apiVersion: v1
kind: Service
metadata:
  name: ram-8080
  namespace: sapidblue
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: ram-8080