---
apiVersion: v1
kind: Service
metadata:
  name: utility-8000
  namespace: sapidblue
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: utility-8000