apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: lcms-node-vpa
  namespace: dev
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: lcms-node
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 1
          memory: 100Mi
        maxAllowed:
          cpu: 2
          memory: 2
        controlledResources: ["cpu", "memory"]