apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: qa-data-mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers:
        - name: mysql
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
            - "--sql-mode="
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: V44MX2PdXxXF84q7
          ports:
            - containerPort: 3306
              name: mysql    
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql    
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance                                            
      volumes: 
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: sapidblue-mysql-data
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script