apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: qa-data-mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 30037
    nodePort: 30037
    targetPort: 3306